name: nugurang-back
on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.14
      uses: actions/setup-java@v1
      with:
        java-version: 1.14
    - name: Build with Gradle
      run: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_ID=${{ secrets.OAUTH_CLIENT_ID }} SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_SECRET=${{ secrets.OAUTH_CLIENT_SECRET }} ./gradlew build --info
      working-directory: nugurang-back
